KnowniesWeb/Models/LoginForm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KnowniesWeb.Models
{
    public class LoginForm
    {
        private string userName;

        public string UserName
        {
            get { return userName; }
            set { userName = value; }
        }

        private string password;

        public string Password
        {
            get { return password; }
            set { password = value; }
        }

        private string errorMessage;

        public string ErrorMessage
        {
            get { return errorMessage; }
            set { errorMessage = value; }
        }
        
    }
}

KnowniesWeb/Models/MainPageModel.cs
using KnowniesWeb.UserService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KnowniesWeb.Models
{
    public class MainPageModel
    {
        public LoginForm LoginForm { get; set; }
        public User UserParam { get; set; }
        public T_USER User { get; set; }
        public UserInfo UserInfo { get; set; }

        public Result Result { get; set; }
        public string viewpart { get; set; }

        public string RetrivePasswordKey { get; set; }
    }
}

KnowniesWeb/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KnowniesWeb.UserService;

namespace KnowniesWeb.Models
{
    public class User: T_USER
    {
        [Compare("PASSWORD")]
        public string ConfirmPassword { get; set; }
        
    }
}

KnowniesWeb/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KnowniesWeb.Models;
using KnowniesWeb.UserService;

namespace KnowniesWeb.Controllers
{
    public class MainController : Controller
    {
        //
        // GET: /Main/
        UserServiceClient oUserClient;

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(MainPageModel model)
        {
            oUserClient = new UserService.UserServiceClient();
            UserInfo user = oUserClient.AuthenticateUser(model.LoginForm.UserName, model.LoginForm.Password);

            if (user != null)
                return View("UserProfile", new MainPageModel { UserInfo = user, Result = new Result { IsCompleted = true } });
            else
                return View("Index", new MainPageModel { Result = new Result { IsCompleted = false, ErrorMessage = "Hatalı kullanıcı" } });
        }

        public ActionResult Signup()
        {
            return View("Signup");
        }

        public ActionResult SignupResult(T_USER user)
        {
            oUserClient = new UserServiceClient();
            user.CREATED_DATETIME = DateTime.Now;
            user.ROLE_ID = 1;
            Result oResult = null;
            MainPageModel oModel = new MainPageModel();
            if (user.CONFIRM_PASSWORD != user.PASSWORD)
                oResult = new Result { IsCompleted = false, ErrorMessage = "Şifre ve şifre tekrarı aynı değil." };
            else
            {
                oResult = oUserClient.CreateUser(user);
                oModel.UserInfo = new UserInfo { Name = user.NAME, Surname = user.SURNAME };
            }

            oModel.Result = oResult;

            if (oResult.IsCompleted)
                return View("UserProfile", oModel);
            else
                return View("Signup", oModel);
        }

        public ActionResult ForgetPassword() 
        {
            return View("Index", new MainPageModel { viewpart = "forgetpassword" });
        }

        public ActionResult ForgetPasswordResult(MainPageModel model)
        {
            oUserClient = new UserServiceClient();
            Result oResult = oUserClient.SendNewPasswordLink(model.RetrivePasswordKey);
            return View("Index", new MainPageModel { viewpart = "forgetpassword", Result = oResult });
        
        }

    }
}

KnowniesWeb/Views/Main/Index.cshtml
@{
    ViewBag.Title = "Index";
}
@model KnowniesWeb.Models.MainPageModel

<h2>Index</h2>

@if (Model == null || (Model != null && Model.viewpart != "forgetpassword"))
{
    using (Html.BeginForm("Login", "Main", FormMethod.Post))
    {
        <table>
            <tr>
                <td>
                    @Html.Label("Kullanıcı Adı:")
                </td>
                <td>
                    @Html.TextBoxFor(m => m.LoginForm.UserName)
                </td>
            </tr>
            <tr>
                <td>

                    @Html.Label("Şifre:")
                </td>
                <td>
                    @Html.TextBoxFor(m => m.LoginForm.Password)
                </td>
            </tr>
            <tr>
                <td colspan="2"><input type="submit" value="Giriş" />@Html.ActionLink("Şifremi Unuttum", "ForgetPassword")@Html.ActionLink("Kaydol", "Signup")</td>
            </tr>

            @Html.LabelForModel(Model != null && Model.Result != null && !Model.Result.IsCompleted ? Model.Result.ErrorMessage : "")
        </table>
    }
}
else if(Model != null && Model.viewpart == "forgetpassword")
{
    using (Html.BeginForm("ForgetPasswordResult", "Main", FormMethod.Post))
    {
        <table>
            <tr>
                <td>
                    @Html.Label("Kullanıcı Adı veya Email Giriniz")
                </td>
                <td>
                    @Html.TextBoxFor(m => m.RetrivePasswordKey)
                </td>
            </tr>
            <tr>
                <td colspan="2"><input type="submit" value="Gönder" /></td>
            </tr>
            <tr>
                <td colspan="2">
                    @if (Model != null && Model.Result != null)
                    {
                        if (Model.Result.IsCompleted)
                        {
                            Html.Label("Şifre sıfırlama emailiniz kayıtlı email adresinize iltilmiştir");
                        }
                        else
                        {
                            @Html.LabelForModel(Model.Result.ErrorMessage)
                        }
                    }


                </td>

            </tr>


        </table>
    }

}

KnowniesWeb/Views/Main/Signup.cshtml
@{
    ViewBag.Title = "Signup";
}
@model KnowniesWeb.Models.MainPageModel
<h2>Signup</h2>
@using (Html.BeginForm("SignupResult", "Main", FormMethod.Post)) {
<table>
    <tr>
        <td>@Html.Label("Kullanıcı Adı")</td>
        <td>@Html.TextBoxFor(m=>m.User.USER_NAME)</td>
       
    </tr>
    <tr>
        <td>@Html.Label("Şifre")</td>
        <td>@Html.PasswordFor(m => m.User.PASSWORD)</td>
    </tr>
    <tr>
        <td>@Html.Label("Şifre Tekrar")</td>
        <td>@Html.PasswordFor(m => m.User.CONFIRM_PASSWORD)</td>
    </tr>
    <tr>
        <td>@Html.Label("Email")</td>
        <td>@Html.TextBoxFor(m => m.User.EMAIL)</td>
    </tr>
    <tr>
        <td>@Html.Label("Ad")</td>
        <td>@Html.TextBoxFor(m => m.User.NAME)</td>
    </tr>
    <tr>
        <td>@Html.Label("Soyad")</td>
        <td>@Html.TextBoxFor(m => m.User.SURNAME)</td>
    </tr>
    <tr>
        <td>@Html.Label("Yaş")</td>
        <td>@Html.TextBoxFor(m => m.User.AGE)</td>
    </tr>
    <tr>
        <td>@Html.Label("Telefon")</td>
        <td>@Html.TextBoxFor(m => m.User.PHONE)</td>
    </tr>
    <tr>
        <td colspan="2"><input type="submit" value="Kaydol" />@Html.LabelForModel(Model!= null && Model.Result != null && !Model.Result.IsCompleted ? Model.Result.ErrorMessage : "")</td>
        
    </tr>
    <tr>
        <td colspan="2"></td>

    </tr>
</table>
}

KnowniesWeb/Views/Main/UserProfile.cshtml
@{
    ViewBag.Title = "UserProfile";
}
@model KnowniesWeb.Models.MainPageModel
<h2>UserProfile</h2>
<table>
    <tr>
        <td>@Html.Label(Model.UserInfo.Name)</td>

    </tr>
    <tr><td>@Html.Label(Model.UserInfo.Surname)</td></tr>
    

</table>